### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by uhlhosting** [wkicior/mandayFaktura#2]
Hi,

I installed the app, yet I do not know how to change the language to english.

**Comment by wkicior** [comment]
Hi, thanks for trying mandayFaktura. Unfortunately, as the application has been designed/optimized for usage on the Polish market only, I haven't yet implemented the support for i18n. I'll add it as the next priority and hopefully deliver the English support within a couple of weeks. Sorry for the inconvenience and thanks for raising the issue.

**Comment by wkicior** [comment]
I've added support for EN language. My next step would be to provide currencies other than PLN. I'll provide it in next couple of weeks.

**Comment by uhlhosting** [comment]
@wkicior thanks! looking forward to other currencies, EUR, CHF, CZK maybe...

**Comment by wkicior** [comment]
> looking forward to other currencies, EUR, CHF, CZK maybe...

@uhlhosting Done - release 0.2.1. The default currency can be defined in the settings.

**Comment by uhlhosting** [comment]
Installing now setting it up and letting you know! Thank you!
