### ISSUE TITLE
Minor issues on PDF Generated

### ISSUE THREAD

**Issue by uhlhosting** [wkicior/mandayFaktura#6]
<img width="233" alt="image" src="https://github.com/wkicior/mandayFaktura/assets/6324047/63855feb-44af-4a8e-8b38-227731f14422">

Hi,

it seems there is a issue with the way the price displayed written is shown, the 0/100 EUR part not sure it is the way its meant to be?

**Comment by wkicior** [comment]
Hi,
it's meant to be the euro cents part. I believe I copied the approach from the previous invoicing software and it worked for me for a couple of years.
But I agree - it's confusing and not really 'in words'. I'll fix that.
700,00 EUR would display as 'seven hundred EUR'
700,25 EUR would display as 'seven hundred EUR twenty five c'

I'll fix that only for some most popular currencies, though. I won't be able to find out how 'cents' equivalents are abbreviated for most of them.

**Comment by uhlhosting** [comment]
I suggest you look into: https://bitbucket.org/lubo08/s-invoice/issues?status=new&status=open they did a great project, yet on latest releases of Sonoma, it stopped working, it gives only a blank screen. yet been using this for over 3 4 years, and no issues at all. has a nice to use UI, and has a built in mail for sending mails. With your knowledge id never reinvent the wheel, yet surely reuse portions of that code that can be used.

**Comment by wkicior** [comment]
Thanks I'll have a look. I have improved the cents part spelling in v. 0.2.2.
